### ISSUE TITLE
Sorting Products In Categories Not Working

### ISSUE THREAD

**Issue by vrextar** [numinix/tableau#17]
When I try to sort a category of products, none of the options work. It reloads the page but it doesn't actually sort them in any fashion as far as I can tell. Any ideas how to fix this? I am running Tableau on a local copy test site and also tried installing a brand new copy of Zen Cart and Tableau and it still isn't working. Thanks for any help you can provide.

**Comment by jefflew** [comment]
We'll check if this is the case on our demo site.  If not, it must be related to your specific setup.  We do offer paid support if you'd like us to reinstall the template for you on a publicly accessible server.

**Comment by vrextar** [comment]
Thanks for the help. I checked the demo site myself after reading your comment and it is happening on there as well. Well in at least one category anyways. I checked the DVD Action Movies category. Thanks again for the help, it is appreciated. Love the template. :)

**Comment by ms1225** [comment]
Same problem here, found a temporary fix in the ZenCart forums here - https://www.zen-cart.com/showthread.php?212899-Tableau-Responsive-Theme-Support-Thread&p=1282536#post1282536

**Comment by ms1225** [comment]
This has been kinda of fixed with the "sortby" being added to the main_template_vars.php file, but now I noticed that if there is a default sort order set in the Admin ->Configuration -> Product Listing you cannot select that sort option in the drop down....

**Comment by jefflew** [comment]
Tableau does not currently support that configuration option since it's not
using the default system for sorting.  We plan to move back to the default
system and will be releasing a new version next week.

On Thu, Oct 8, 2015 at 8:11 AM, ms1225 <notifications@github.com> wrote:

> This has been kinda of fixed with the "sortby" being added to the
> main_template_vars.php file, but now I noticed that if there is a default
> sort order set in the Admin ->Configuration -> Product Listing you cannot
> select that sort option in the drop down....
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numinix/tableau/issues/17#issuecomment-146574989>.
>



-- 

*Jeff Lew*
President

*Phone:* 1-855-686-4649 Ext 700
*Email/Gchat:* jlew@numinix.com
*Skype:* numinix
[image: Numinix] <http://www.numinix.com/>

[image: Facebook] <http://www.facebook.com/numinix> [image: Twitter]
<http://twitter.com/numinix> [image: Google+]
<https://plus.google.com/+Numinix> [image: Instagram]
<http://instagram.com/numinixwebdev> [image: Pinterest]
<http://www.pinterest.com/numinix> [image: Blog]
<http://www.numinix.com/blog/?feed=rss2>

**Comment by malloyd** [comment]
Afternoon all, I'm just about to tidy up the sort feature on my site and wondered if the new version using the default sort system has been created please? Thanks a lot, Mark.

**Comment by jonorherrington** [comment]
Sort accounts for default setting defined in the product listing config page under the default label.

**Comment by ms1225** [comment]
Not really closed... I just updated to 1.6.13 and the tpl_modules_product_listing.php file included made a mess of this. Sort didn't work properly, or respect the default setting in admin. I went back to the fix I mentioned above.

**Comment by jonorherrington** [comment]
Can you please let us know what you are inserting into the default sort field on the admin side? We have tested changing the value of the default sort under the configuration several times and have gotten the expected results. How is the tpl_modules_product_listing.php file making a mess of things for you? All that is going on there is that the dropdown is being created for the client side.
